version: 2
jobs:
  build:
    docker:
      - image: circleci/builder-base
    steps:
      - checkout
      - run: |
          apt-get update &&
          apt-get install -y unzip &&
          wget https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip &&
          unzip packer_1.2.2_linux_amd64.zip &&
          mv packer /usr/local/bin/packer
      - run: /usr/local/bin/packer build awsne-packer.json
